-- ============================================================================
-- Import MATERIALIEN aus "Z_Kalkulation Vorlage 2026 Material und Positionen.xlsx"
-- (Arbeitsmappe MATERIALIEN: 184 Einträge inkl. 8 Stundensätze).
-- Materialien ohne Preis in der Excel kommen mit EK 0 rein (im Katalog nachpflegen).
-- Idempotent: bereits vorhandene Material-Namen werden übersprungen.
-- ============================================================================

WITH admin_user AS (
  SELECT user_id FROM public.user_roles WHERE role = 'administrator' LIMIT 1
),
neu (name, kurzbezeichnung, einheit, ek, kategorie) AS (
  VALUES
  ('Facharbeiterstunde', 'Facharbeiterstunde', 'Std', 54.0, 'Stundensätze'),
  ('Baumeisterstunde', 'Baumeisterstunde', 'Std', 105.0, 'Stundensätze'),
  ('Lehrling Stunde', 'Lehrling Stunde', 'Std', 48.0, 'Stundensätze'),
  ('LKW mit Hiab', 'LKW mit Hiab', 'Std', 110.0, 'Stundensätze'),
  ('Regiestunde Facharbeiter', 'Regiestunde Facharbeiter', 'Std', 58.0, 'Stundensätze'),
  ('Regiestunde Lehrling', 'Regiestunde Lehrling', 'Std', 52.0, 'Stundensätze'),
  ('Kranfahrer', 'Kranfahrer', 'Std', 56.0, 'Stundensätze'),
  ('Maschinenstunde', 'Maschinenstunde', 'Std', 75.0, 'Stundensätze'),
  ('Kontainer groß Anfahrt&Abfuhr', 'Kontainer groß Anfahrt&Abfuhr', 'to', 172.7, 'Entsorgung'),
  ('Kontainer klein Anfahrt&Abfuhr', 'Kontainer klein Anfahrt&Abfuhr', 'to', 189.4, 'Entsorgung'),
  ('Entsorgung Holz unrein-stark verunreinigt', 'Entsorgung Holz unrein-stark verunreinigt', 'to', 250.0, 'Entsorgung'),
  ('Entsorgung Holz rein', 'Entsorgung Holz rein', 'to', 100.9, 'Entsorgung'),
  ('Entsorgung Bitumen', 'Entsorgung Bitumen', 'to', 280.0, 'Entsorgung'),
  ('Entsorgung Bauschutt', 'Entsorgung Bauschutt', 'to', 51.1, 'Entsorgung'),
  ('Konstruktionsholz BSH Gl24h Fichte sicht-Lagerware', 'Konstruktionsholz BSH Gl24h Fichte sicht-Lagerware', 'm3', 640.0, 'Holz'),
  ('Konstruktionsholz BSH Gl24h Fichte sicht-Kommissionierte Ware', 'Konstruktionsholz BSH Gl24h Fichte sicht-Kommissionierte Ware', 'm3', 640.0, 'Holz'),
  ('Konstruktionsholz BSH Gl24h Fichte nicht sicht-Kommissionierte Ware', 'Konstruktionsholz BSH Gl24h Fichte nicht sicht-Kommissionierte Ware', 'm3', 620.0, 'Holz'),
  ('Konstruktionsholz KVH C24 Fichte sicht-Lagerware 6cm breit', 'Konstruktionsholz KVH C24 Fichte sicht-Lagerware 6cm breit', 'm3', 450.0, 'Holz'),
  ('Konstruktionsholz KVH C24 Fichte sicht-Lagerware 8cm breit', 'Konstruktionsholz KVH C24 Fichte sicht-Lagerware 8cm breit', 'm3', 455.0, 'Holz'),
  ('Konstruktionsholz KVH C24 Fichte sicht-Lagerware 10cm breit', 'Konstruktionsholz KVH C24 Fichte sicht-Lagerware 10cm breit', 'm3', 460.0, 'Holz'),
  ('BSH Deckenelement sicht 14cm', 'BSH Deckenelement sicht 14cm', 'm3', 615.0, 'Holz'),
  ('BSH Deckenelement nicht sicht 14cm', 'BSH Deckenelement nicht sicht 14cm', 'm3', 600.0, 'Holz'),
  ('BSH Deckenelement sicht 16cm', 'BSH Deckenelement sicht 16cm', 'm3', 615.0, 'Holz'),
  ('BSH Deckenelement nicht sicht 16cm', 'BSH Deckenelement nicht sicht 16cm', 'm3', 600.0, 'Holz'),
  ('Lärchen Bauholz sägerau ca.15-20%', 'Lärchen Bauholz sägerau ca.15-20%', 'm3', 850.0, 'Holz'),
  ('Latten Lärche sägerau 12x12cm', 'Latten Lärche sägerau 12x12cm', 'm3', 900.0, 'Holz'),
  ('Fichten Bauholz sägerau 15-20%', 'Fichten Bauholz sägerau 15-20%', 'm3', 380.0, 'Holz'),
  ('Dachlatten Fichte sägerau 4x5cm', 'Dachlatten Fichte sägerau 4x5cm', 'm3', 340.0, 'Holz'),
  ('Konterlatten Fichte sägerau 5x8cm', 'Konterlatten Fichte sägerau 5x8cm', 'm3', 340.0, 'Holz'),
  ('Konterlatten Fichte sägerau 6x8cm', 'Konterlatten Fichte sägerau 6x8cm', 'm3', 340.0, 'Holz'),
  ('Konterlatten Fichte sägerau 8x8cm', 'Konterlatten Fichte sägerau 8x8cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 5x3cm', 'Latten Fichte sägerau 5x3cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 5x6cm', 'Latten Fichte sägerau 5x6cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 6x10cm', 'Latten Fichte sägerau 6x10cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 6x12cm', 'Latten Fichte sägerau 6x12cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 6x16cm', 'Latten Fichte sägerau 6x16cm', 'm3', 340.0, 'Holz'),
  ('Latten Fichte sägerau 6x16cm', 'Latten Fichte sägerau 6x16cm', 'm3', 380.0, 'Holz'),
  ('Latten Fichte sägerau 8x20cm', 'Latten Fichte sägerau 8x20cm', 'm3', 380.0, 'Holz'),
  ('Rahmenholz trocken Fichte 6x16cm', 'Rahmenholz trocken Fichte 6x16cm', 'm3', 555.0, 'Holz'),
  ('Rahmenholz trocken Fichte 6x20cm', 'Rahmenholz trocken Fichte 6x20cm', 'm3', 555.0, 'Holz'),
  ('Rahmenholz trocken Fichte 8x16cm', 'Rahmenholz trocken Fichte 8x16cm', 'm3', 555.0, 'Holz'),
  ('Rahmenholz trocken Fichte 8x20cm', 'Rahmenholz trocken Fichte 8x20cm', 'm3', 555.0, 'Holz'),
  ('Rahmenholz trocken Fichte 6x24cm', 'Rahmenholz trocken Fichte 6x24cm', 'm3', 555.0, 'Holz'),
  ('Rahmenholz trocken Fichte 8x24cm', 'Rahmenholz trocken Fichte 8x24cm', 'm3', 555.0, 'Holz'),
  ('Rauschalung 24mm Fichte sägerau', 'Rauschalung 24mm Fichte sägerau', 'm3', 310.0, 'Holz'),
  ('Fasenschalung 19mm N+F gehobelt, gefast, natur A/B-Qualität', 'Fasenschalung 19mm N+F gehobelt, gefast, natur A/B-Qualität', 'm2', 11.5, 'Holz'),
  ('Fasenschalung 23mm N+F gehobelt, gefast, natur A/B-Qualität', 'Fasenschalung 23mm N+F gehobelt, gefast, natur A/B-Qualität', 'm2', 13.9, 'Holz'),
  ('Fasenschalung 23mm N+F gehobelt, gefast, natur B/C-Qualität', 'Fasenschalung 23mm N+F gehobelt, gefast, natur B/C-Qualität', 'm2', 9.5, 'Holz'),
  ('Glattkantbrett Fichte gehobelt, gefast, natur 23x200mm', 'Glattkantbrett Fichte gehobelt, gefast, natur 23x200mm', 'm2', 20.0, 'Holz'),
  ('Dreischichtplatte Fichte 19mm A/B Qualität', 'Dreischichtplatte Fichte 19mm A/B Qualität', 'm2', 23.2, 'Holz'),
  ('Dreischichtplatte Fichte 19mm B/C Qualität', 'Dreischichtplatte Fichte 19mm B/C Qualität', 'm2', 20.2, 'Holz'),
  ('Dreischichtplatte Fichte 19mm D/D Qualität', 'Dreischichtplatte Fichte 19mm D/D Qualität', 'm2', 15.6, 'Holz'),
  ('Dreischichtplatte Fichte 27mm B/C Qualität', 'Dreischichtplatte Fichte 27mm B/C Qualität', 'm2', 26.5, 'Holz'),
  ('Dreischichtplatte Fichte 27mm D/D Qualität', 'Dreischichtplatte Fichte 27mm D/D Qualität', 'm2', 20.3, 'Holz'),
  ('OSB-Platte 15mm N+F ungeschl.', 'OSB-Platte 15mm N+F ungeschl.', 'm2', 6.5, 'Holz'),
  ('OSB-Platte 18mm N+F ungeschl.', 'OSB-Platte 18mm N+F ungeschl.', 'm2', 7.8, 'Holz'),
  ('OSB-Platte 22mm N+F ungeschl.', 'OSB-Platte 22mm N+F ungeschl.', 'm2', 9.55, 'Holz'),
  ('DWD-Platte 16mm N+F', 'DWD-Platte 16mm N+F', 'm2', 6.7, 'Holz'),
  ('Holzfaserplatte 60mm N+F verputzbar 150kg/m3', 'Holzfaserplatte 60mm N+F verputzbar 150kg/m3', 'm2', 11.0, 'Holz'),
  ('Nageldichtband PE 60mm-PE NDB ESK (20lfm)', 'Nageldichtband PE 60mm-PE NDB ESK (20lfm)', 'm', 0.3, 'Befestigung'),
  ('Nageldichtband PE 80mm-PE NDB ESK (20lfm)', 'Nageldichtband PE 80mm-PE NDB ESK (20lfm)', 'm', 0.43, 'Befestigung'),
  ('Nageldichtband bituminös 60mm-Omega NDB ESK (10lfm)', 'Nageldichtband bituminös 60mm-Omega NDB ESK (10lfm)', 'm', 1.06, 'Befestigung'),
  ('Nageldichtband bituminös 80mm-Omega NDB ESK (10lfm)', 'Nageldichtband bituminös 80mm-Omega NDB ESK (10lfm)', 'm', 1.23, 'Befestigung'),
  ('Bitumenbahn 1,5mm nsk', 'Bitumenbahn 1,5mm nsk', 'm2', 4.07, 'Bahnen & Abdichtung'),
  ('Bitumenbahn 3mm nsk', 'Bitumenbahn 3mm nsk', 'm2', 6.39, 'Bahnen & Abdichtung'),
  ('Bitumenbahn 4mm EKV-4K', 'Bitumenbahn 4mm EKV-4K', 'm2', 6.27, 'Bahnen & Abdichtung'),
  ('Bitumenbahn 5mm beschiefert EKV- 5S', 'Bitumenbahn 5mm beschiefert EKV- 5S', 'm2', 18.0, 'Bahnen & Abdichtung'),
  ('Dampfdiffusionsoffene Dachbahn - Monotop 330-6 Monate UV-beständig, ab 5°DN 1,5m', 'Dampfdiffusionsoffene Dachbahn - Monotop 330-6 Monate UV-beständig, ab 5°DN 1,5m', 'm2', 6.69, 'Bahnen & Abdichtung'),
  ('Dampfdiffusionsoffene Dachbahn - UDOs 330  quellgeschweißt-5 Monate UV-beständig, ab 1,5°DN 1,5m', 'Dampfdiffusionsoffene Dachbahn - UDOs 330  quellgeschweißt-5 Monate UV-beständig, ab 1,5°DN 1,5m', 'm2', 8.6001, 'Bahnen & Abdichtung'),
  ('Dampfdiffusionsoffene Dachbahn - UDOs 330  quellgeschweißt-5 Monate UV-beständig, ab 1,5°DN 3m', 'Dampfdiffusionsoffene Dachbahn - UDOs 330  quellgeschweißt-5 Monate UV-beständig, ab 1,5°DN 3m', 'm2', 8.7091, 'Bahnen & Abdichtung'),
  ('Quellschweißmittel-QSM Omega', 'Quellschweißmittel-QSM Omega', 'Do', 26.13, 'Sonstiges Material'),
  ('Klebeband Airstop 50mm (50m)', 'Klebeband Airstop 50mm (50m)', 'm', 0.54, 'Befestigung'),
  ('Klebeband Airstop 60mm (50m)', 'Klebeband Airstop 60mm (50m)', 'm', 0.62, 'Befestigung'),
  ('Klebeband Airstop 100mm (50m)', 'Klebeband Airstop 100mm (50m)', 'm', 1.03, 'Befestigung'),
  ('Klebeband flex Airstop 50mm (25m)', 'Klebeband flex Airstop 50mm (25m)', 'm', 0.55, 'Befestigung'),
  ('Klebeband flex Airstop 75mm (25m)', 'Klebeband flex Airstop 75mm (25m)', 'm', 1.0, 'Befestigung'),
  ('Klebepaste Omega Frozen', 'Klebepaste Omega Frozen', 'Stk', 10.49, 'Sonstiges Material'),
  ('Dichtmasse - Airstop Sprint', 'Dichtmasse - Airstop Sprint', 'Stk', 6.99, 'Bahnen & Abdichtung'),
  ('Dichtmasse - Airstop Quilli', 'Dichtmasse - Airstop Quilli', 'Stk', 9.0, 'Bahnen & Abdichtung'),
  ('Kaminecke-Omega UDOs Außenecke', 'Kaminecke-Omega UDOs Außenecke', 'Stk', 8.02, 'Sonstiges Material'),
  ('Fassadenbahn - Omega Winddichtung -2 Monate UV-beständig 1,50x50m', 'Fassadenbahn - Omega Winddichtung -2 Monate UV-beständig 1,50x50m', 'm2', 1.07, 'Bahnen & Abdichtung'),
  ('Fassadenbahn - Omega Winddichtung -2 Monate UV-beständig 3,0x50m', 'Fassadenbahn - Omega Winddichtung -2 Monate UV-beständig 3,0x50m', 'm2', 1.12, 'Bahnen & Abdichtung'),
  ('Fassadenbahn - Omega G20 Winddichtung -dauerhaft UV-beständig 1,50x50m', 'Fassadenbahn - Omega G20 Winddichtung -dauerhaft UV-beständig 1,50x50m', 'm2', 3.27, 'Bahnen & Abdichtung'),
  ('Fassadenbahn - Omega G20 Winddichtung -dauerhaft UV-beständig', 'Fassadenbahn - Omega G20 Winddichtung -dauerhaft UV-beständig', 'm2', 3.32, 'Bahnen & Abdichtung'),
  ('Fassadenband - Omega UVKB 53mm (25m)', 'Fassadenband - Omega UVKB 53mm (25m)', 'm2', 0.74, 'Befestigung'),
  ('EPDM Band -Fascon 1,2mm UV stabil 80mm (20m)', 'EPDM Band -Fascon 1,2mm UV stabil 80mm (20m)', 'm', 2.51, 'Befestigung'),
  ('Dampfbremse DIVA Airstop-feuchtevariabel sd-Wert:0,5-30m 1,5x50m', 'Dampfbremse DIVA Airstop-feuchtevariabel sd-Wert:0,5-30m 1,5x50m', 'm2', 3.09, 'Sonstiges Material'),
  ('Dampfbremse Airstop VAP - sd-Wert: 100m (3mx50lfm)', 'Dampfbremse Airstop VAP - sd-Wert: 100m (3mx50lfm)', 'm2', 1.3, 'Sonstiges Material'),
  ('Fensterband -Isowindow FEBA Soft WS-für innen- 6Monate UV-beständig 75mmx25m', 'Fensterband -Isowindow FEBA Soft WS-für innen- 6Monate UV-beständig 75mmx25m', 'm', 1.5, 'Befestigung'),
  ('Fensterband -Isowindow UVAU WS-für außen- 12 Monate UV-beständig 80mmx25m', 'Fensterband -Isowindow UVAU WS-für außen- 12 Monate UV-beständig 80mmx25m', 'm', 1.5, 'Befestigung'),
  ('Omega 125 Dachbahn für Deckeneinschlag 0,75mx50m-75m2', 'Omega 125 Dachbahn für Deckeneinschlag 0,75mx50m-75m2', 'm2', 1.14, 'Bahnen & Abdichtung'),
  ('Bauschaum', 'Bauschaum', 'Do', 5.0, 'Sonstiges Material'),
  ('Weichzellschaum', 'Weichzellschaum', 'Do', 11.55, 'Sonstiges Material'),
  ('Weichzellschaum-Herametic', 'Weichzellschaum-Herametic', 'Do', 9.42, 'Sonstiges Material'),
  ('Klebeband - Butyl-Klebeband Omega Plasto Band-75mm- 4 Monate UV-beständig 25m', 'Klebeband - Butyl-Klebeband Omega Plasto Band-75mm- 4 Monate UV-beständig 25m', 'm', 1.34, 'Befestigung'),
  ('Klebeband - Butyl-Klebeband Omega Plasto Band-100mm- 4 Monate UV-beständig 25m', 'Klebeband - Butyl-Klebeband Omega Plasto Band-100mm- 4 Monate UV-beständig 25m', 'm', 1.83, 'Befestigung'),
  ('Klebeband - Butyl-Klebeband Omega Plasto Band-160mm- 4 Monate UV-beständig 25m', 'Klebeband - Butyl-Klebeband Omega Plasto Band-160mm- 4 Monate UV-beständig 25m', 'm', 2.47, 'Befestigung'),
  ('Klebeband - Butyl-Klebeband Omega Plasto Band- 200mm- 4 Monate UV-beständig 25m', 'Klebeband - Butyl-Klebeband Omega Plasto Band- 200mm- 4 Monate UV-beständig 25m', 'm', 5.08, 'Befestigung'),
  ('Bitumenkautschukband-Airstop VBB Vlies-200mm-100-100 Linerteilung- 4 Monate UV-beständig (10m)', 'Bitumenkautschukband-Airstop VBB Vlies-200mm-100-100 Linerteilung- 4 Monate UV-beständig (10m)', 'm', 4.15, 'Befestigung'),
  ('Haftprimer Bubi LF', 'Haftprimer Bubi LF', 'Do', 25.82, 'Bahnen & Abdichtung'),
  ('Sprühprimer Uni', 'Sprühprimer Uni', 'Do', 11.49, 'Bahnen & Abdichtung'),
  ('Dichtpaste-Omega Pobit 10kg', 'Dichtpaste-Omega Pobit 10kg', 'Kübel', 8.12, 'Bahnen & Abdichtung'),
  ('Bewehrungsband -Omega Pobit - 150mmx50m', 'Bewehrungsband -Omega Pobit - 150mmx50m', 'm', 1.141, 'Befestigung'),
  ('Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-150mm/10mmx25m', 'Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-150mm/10mmx25m', 'm', 3.26, 'Bahnen & Abdichtung'),
  ('Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-200mm/10mmx25m', 'Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-200mm/10mmx25m', 'm', 3.68, 'Bahnen & Abdichtung'),
  ('Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-250mm/20mm/20m', 'Schlauchdichtung-EPDM - Zellkautschuk -ST Dichtung-250mm/20mm/20m', 'm', 8.62, 'Bahnen & Abdichtung'),
  ('Zellulose 17-24cm Dämmstärke Wand ca.3,71Sack/m3', 'Zellulose 17-24cm Dämmstärke Wand ca.3,71Sack/m3', 'm3', 78.0, 'Dämmung'),
  ('Zellulose Löcher bohren u schließen ca. 0,82Stk/m2', 'Zellulose Löcher bohren u schließen ca. 0,82Stk/m2', 'Stk', 2.94, 'Dämmung'),
  ('Zellulose Dichtplaster', 'Zellulose Dichtplaster', 'Stk', 1.0, 'Dämmung'),
  ('Zellulose An-und Abreise >50km', 'Zellulose An-und Abreise >50km', 'm2', 150.0, 'Dämmung'),
  ('Zellulose Baustelleneinrichtung allgemein', 'Zellulose Baustelleneinrichtung allgemein', 'Pa', 31.0, 'Dämmung'),
  ('Zellulose Baustelleneinrichtung sepperat', 'Zellulose Baustelleneinrichtung sepperat', 'Pa', 220.0, 'Dämmung'),
  ('Zellulose Helfer ohne bauseitig gestellte Hilfe 10%vom Auftrag', 'Zellulose Helfer ohne bauseitig gestellte Hilfe 10%vom Auftrag', 'Std', 55.0, 'Dämmung'),
  ('Lieferpauschale', 'Lieferpauschale', 'Pa', 0.0, 'Sonstiges Material'),
  ('Aufdachdämmung 16cm Bauder Pir Plus', 'Aufdachdämmung 16cm Bauder Pir Plus', 'm2', 46.0, 'Dämmung'),
  ('Aufdachdämmung 18cm Bauder Pir Plus', 'Aufdachdämmung 18cm Bauder Pir Plus', 'm2', 51.3, 'Dämmung'),
  ('Aufdachdämmung 20cm Bauder Pir Plus', 'Aufdachdämmung 20cm Bauder Pir Plus', 'm2', 57.0, 'Dämmung'),
  ('Bauder PMK Band', 'Bauder PMK Band', 'm', 5.7, 'Befestigung'),
  ('Mineralwolle Trennwandfilz 10cm lambda 0,033', 'Mineralwolle Trennwandfilz 10cm lambda 0,033', 'm2', 7.33, 'Dämmung'),
  ('Mineralwolle Trennwandfilz 12cm lambda 0,033', 'Mineralwolle Trennwandfilz 12cm lambda 0,033', 'm2', 8.8, 'Dämmung'),
  ('Mineralwolle Trennwandfilz 16cm lambda 0,033 120cm', 'Mineralwolle Trennwandfilz 16cm lambda 0,033 120cm', 'm2', 11.73, 'Dämmung'),
  ('Mineralwolle Trennwandfilz 20cm lambda 0,033 120cm', 'Mineralwolle Trennwandfilz 20cm lambda 0,033 120cm', 'm2', 14.64, 'Dämmung'),
  ('Mineralwolle Trennwandfilz 16cm lambda 0,033 geschnitten 57,5cm', 'Mineralwolle Trennwandfilz 16cm lambda 0,033 geschnitten 57,5cm', 'm2', 12.27, 'Dämmung'),
  ('Mineralwolle Trennwandfilz 20cm lambda 0,033 geschnitten 57,5cm', 'Mineralwolle Trennwandfilz 20cm lambda 0,033 geschnitten 57,5cm', 'm2', 15.36, 'Dämmung'),
  ('Mineralwolldämmplatten Fassade 6cm lambda 0,038', 'Mineralwolldämmplatten Fassade 6cm lambda 0,038', 'm2', 0.0, 'Holz'),
  ('Mineralwolldämmplatten Fassade 8cm lambda 0,038', 'Mineralwolldämmplatten Fassade 8cm lambda 0,038', 'm2', 0.0, 'Holz'),
  ('Holzfaserdämmplatten Steico flex 8cm lambda 0,038', 'Holzfaserdämmplatten Steico flex 8cm lambda 0,038', 'm2', 0.0, 'Holz'),
  ('Holzfaserdämmplatten Steico flex 10cm lambda 0,038', 'Holzfaserdämmplatten Steico flex 10cm lambda 0,038', 'm2', 0.0, 'Holz'),
  ('Coilnägel Dachpappnägel', 'Coilnägel Dachpappnägel', 'Rol', 0.0, 'Sonstiges Material'),
  ('Coilnägel 5x70', 'Coilnägel 5x70', 'Rol', 0.0, 'Sonstiges Material'),
  ('Edelstahlklammern 100mm', 'Edelstahlklammern 100mm', 'Stk', 0, 'Befestigung'),
  ('Gewindestangen M16 verzinkt 1m', 'Gewindestangen M16 verzinkt 1m', 'm', 0.0, 'Befestigung'),
  ('Mutter M16 verzinkt', 'Mutter M16 verzinkt', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 5x50 (200)', 'Schrauben 5x50 (200)', 'Stk', 0.024, 'Befestigung'),
  ('Schrauben 5x70 (100)', 'Schrauben 5x70 (100)', 'Stk', 0.034, 'Befestigung'),
  ('Schrauben 5x100 (100)', 'Schrauben 5x100 (100)', 'Stk', 0.053, 'Befestigung'),
  ('Schrauben 6x120 (100)', 'Schrauben 6x120 (100)', 'Stk', 0.074, 'Befestigung'),
  ('Schrauben 6x140 (100)', 'Schrauben 6x140 (100)', 'Stk', 0.091, 'Befestigung'),
  ('Schrauben 6x180 (100)', 'Schrauben 6x180 (100)', 'Stk', 0.162, 'Befestigung'),
  ('Schrauben 8x120 TK  (50)', 'Schrauben 8x120 TK  (50)', 'Stk', 0.15, 'Befestigung'),
  ('Schrauben 8x100 TK (50)', 'Schrauben 8x100 TK (50)', 'Stk', 0.14, 'Befestigung'),
  ('Schrauben 8x180 (100)', 'Schrauben 8x180 (100)', 'Stk', 0.21, 'Befestigung'),
  ('Schrauben 8x200 TK', 'Schrauben 8x200 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x240 TK', 'Schrauben 8x240 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x260 TK (50)', 'Schrauben 8x260 TK (50)', 'Stk', 0.49, 'Befestigung'),
  ('Schrauben 8x280 TK', 'Schrauben 8x280 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x300 TK (50)', 'Schrauben 8x300 TK (50)', 'Stk', 0.58, 'Befestigung'),
  ('Schrauben 8x320 TK', 'Schrauben 8x320 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x340 TK', 'Schrauben 8x340 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x380 TK (50)', 'Schrauben 8x380 TK (50)', 'Stk', 0.81, 'Befestigung'),
  ('Schrauben 8x400 TK', 'Schrauben 8x400 TK', 'Stk', 0.0, 'Befestigung'),
  ('Schrauben 8x440 TK', 'Schrauben 8x440 TK', 'Stk', 0.0, 'Befestigung'),
  ('Transportanker 12x120 (50)', 'Transportanker 12x120 (50)', 'Stk', 1.2118, 'Befestigung'),
  ('Transportanker 12x160 (50)', 'Transportanker 12x160 (50)', 'Stk', 1.4048, 'Befestigung'),
  ('Transportanker 11x200 (25)', 'Transportanker 11x200 (25)', 'Stk', 1.073, 'Befestigung'),
  ('Vollgewindeschrauben VGS 8x240', 'Vollgewindeschrauben VGS 8x240', 'Stk', 0.0, 'Befestigung'),
  ('Vollgewindeschrauben VGS 8x260', 'Vollgewindeschrauben VGS 8x260', 'Stk', 0.0, 'Befestigung'),
  ('Schlaganker-Betonanker 12x150 (25)', 'Schlaganker-Betonanker 12x150 (25)', 'Stk', 1.87, 'Befestigung'),
  ('Schrauben A2 Edelstahl 5x70 (100)', 'Schrauben A2 Edelstahl 5x70 (100)', 'Stk', 0.17, 'Befestigung'),
  ('Schrauben A2 Edelstahl 5x90 (100)', 'Schrauben A2 Edelstahl 5x90 (100)', 'Stk', 0.22, 'Befestigung'),
  ('Pfostenträger verzinkt M24 Gewinde höhenverstellbar 155-210mm Kopfplatte 100x160mm', 'Pfostenträger verzinkt M24 Gewinde höhenverstellbar 155-210mm Kopfplatte 100x160mm', 'Stk', 35.0, 'Befestigung'),
  ('Pfostenträger verzinkt M24 Gewinde höhenverstellbar 155-210mm Kopfplatte rund', 'Pfostenträger verzinkt M24 Gewinde höhenverstellbar 155-210mm Kopfplatte rund', 'Stk', 40.0, 'Befestigung'),
  ('Pfostenträger verzinkt M32 Gewinde höhenverstellbar 155-210mm starke Ausführung', 'Pfostenträger verzinkt M32 Gewinde höhenverstellbar 155-210mm starke Ausführung', 'Stk', 60.0, 'Befestigung'),
  ('Fassadengerüst aufbauen und wieder abbauen', 'Fassadengerüst aufbauen und wieder abbauen', 'm2', 8.5, 'Gerüst'),
  ('Fassadengerüst vorhalten 1VE=1Wo x m2', 'Fassadengerüst vorhalten 1VE=1Wo x m2', 'VE', 0.6, 'Gerüst'),
  ('Fassadengerüst An-und Abtransport in Regie', 'Fassadengerüst An-und Abtransport in Regie', 'Std', 110.0, 'Gerüst'),
  ('Einreichplanung in 3-dacher Ausführung, GR, Schnitte, Ansichten, Bauansuchen, Kubaturber.', 'Einreichplanung in 3-dacher Ausführung, GR, Schnitte, Ansichten, Bauansuchen, Kubaturber.', 'Pa', 0.0, 'Planung'),
  ('Energieausweis', 'Energieausweis', 'Pa', 0.0, 'Planung'),
  ('Lageplan TBO-Plan', 'Lageplan TBO-Plan', 'Pa', 0.0, 'Planung'),
  ('Quellmörtel 0,125m3', 'Quellmörtel 0,125m3', 'Sack', 0.0, 'Sonstiges Material'),
  ('Lochgitter Prefa P10 antrazith bis 15cm 1x gekantet', 'Lochgitter Prefa P10 antrazith bis 15cm 1x gekantet', 'm2', 0.0, 'Spengler'),
  ('GK-BPl. 12,5mm 1250x2000x125mm', 'GK-BPl. 12,5mm 1250x2000x125mm', 'm2', 3.09, 'Platten'),
  ('GK-BPl. 12,5mm 1250x2000x125mm feuerschutz', 'GK-BPl. 12,5mm 1250x2000x125mm feuerschutz', 'm2', 3.68, 'Platten'),
  ('GK-BPl. 12,5mm 1250x2000x125mm feuchteschutz', 'GK-BPl. 12,5mm 1250x2000x125mm feuchteschutz', 'm2', 5.12, 'Platten'),
  ('Fermacelplatte 2000x1250x15mm', 'Fermacelplatte 2000x1250x15mm', 'm2', 12.28, 'Holz'),
  ('Bandblech Prefa P10', 'Bandblech Prefa P10', 'm2', 0.0, 'Spengler'),
  ('Hängerinne 33er rund', 'Hängerinne 33er rund', 'm', 0.0, 'Spengler'),
  ('Rinneneinlaufblech bis 33cm ohne Montage', 'Rinneneinlaufblech bis 33cm ohne Montage', 'm', 0.0, 'Spengler'),
  ('Bögen - Rohrknie 72° 100mm', 'Bögen - Rohrknie 72° 100mm', 'Stk', 0.0, 'Spengler'),
  ('Abschlüsse - Rinnenboden rund 33er', 'Abschlüsse - Rinnenboden rund 33er', 'Stk', 0.0, 'Spengler'),
  ('Rinnenkessel - StandardEinhang rund 33/100', 'Rinnenkessel - StandardEinhang rund 33/100', 'Stk', 0.0, 'Spengler'),
  ('Ablaufrohr 100er a 3m', 'Ablaufrohr 100er a 3m', 'm', 0.0, 'Spengler'),
  ('Windladenverblendung bis 25cm einteilig-3-fach gekantet -ohne Montage', 'Windladenverblendung bis 25cm einteilig-3-fach gekantet -ohne Montage', 'm', 0.0, 'Spengler'),
  ('Windladenabdeckung bis 12cm 3-fach gekantet-ohne Montage', 'Windladenabdeckung bis 12cm 3-fach gekantet-ohne Montage', 'm', 0.0, 'Spengler')
)
INSERT INTO public.invoice_templates
  (user_id, name, kurzbezeichnung, beschreibung, einheit, kategorie, art,
   ek_netto, vk_netto, netto_preis, einzelpreis, brutto_preis, ust_satz,
   ist_kalkuliert, ist_set)
SELECT a.user_id, n.name, n.kurzbezeichnung, n.name, n.einheit, n.kategorie, 'material',
       n.ek, n.ek, n.ek, n.ek, ROUND(n.ek * 1.20, 2), 20,
       false, false
FROM neu n CROSS JOIN admin_user a
WHERE NOT EXISTS (
  SELECT 1 FROM public.invoice_templates t
   WHERE t.name = n.name AND t.art = 'material'
);
